# 配置已取消，使用官方默认源
# 如需重新启用镜像，请取消下方注释

# npmRegistryServer: "https://registry.npmmirror.com/"
# 
# npmScopes:
#   electron:
#     npmRegistryServer: "https://npmmirror.com/mirrors/electron/"
#   node-sass:
#     npmRegistryServer: "https://npmmirror.com/mirrors/node-sass/"
#   chromedriver:
#     npmRegistryServer: "https://npmmirror.com/mirrors/chromedriver"
#   selenium:
#     npmRegistryServer: "https://npmmirror.com/mirrors/selenium"
# 
# npmPublishRegistry: "https://registry.npmmirror.com/"
# 
# unsafeHttpWhitelist:
#   - "npmmirror.com"
# 
# yarnPath: ".yarn/releases/yarn-3.6.3.cjs"
# enableGlobalCache: true
# 
# packageExtensions:
#   sass-loader@*:
#     peerDependencies:
#       webpack: "*" 